import type { MetadataRoute } from "next";

export const dynamic = "force-static";

const BASE_URL = "https://docs.esfera.ai";

export default function sitemap(): MetadataRoute.Sitemap {
  const routes = [
    "/introduccion/",
    "/faq/",
    "/flujo-trabajo/",
    "/ia-chat/",
    "/recursos-visuales/",
    "/primeros-pasos/crear-empresa/",
    "/primeros-pasos/crear-primer-proyecto/",
    "/primeros-pasos/registro/",
    "/primeros-pasos/suscripcion/",
    "/primeros-pasos/verificacion/",
    "/primeros-pasos/olvido-contrasena/",
    "/usuarios/",
    "/usuarios/agregar/",
    "/usuarios/permisos/",
    "/personas/comitentes/",
    "/personas/contratistas/",
    "/personas/proveedores/",
    "/presupuesto/",
    "/presupuesto/presupuesto/",
    "/presupuesto/computo/",
    "/presupuesto/cronograma/",
    "/presupuesto/ejecucion/",
    "/analisis-precio-unitario/",
    "/analisis-precio-unitario/categorias/",
    "/analisis-precio-unitario/grupos/",
    "/analisis-precio-unitario/unidades-de-medida/",
    "/analisis-precio-unitario/materiales-y-servicios/",
    "/analisis-precio-unitario/materiales-y-servicios/crear-nuevo/",
    "/analisis-precio-unitario/materiales-y-servicios/importar-desde-csv/",
    "/analisis-precio-unitario/mano-de-obra/",
    "/analisis-precio-unitario/mano-de-obra/crear-nuevo/",
    "/analisis-precio-unitario/mano-de-obra/importar-desde-csv/",
    "/analisis-precio-unitario/equipos-maquinarias-herramientas/",
    "/analisis-precio-unitario/equipos-maquinarias-herramientas/crear-nuevo/",
    "/analisis-precio-unitario/equipos-maquinarias-herramientas/importar-desde-csv/",
    "/analisis-precio-unitario/items/",
    "/analisis-precio-unitario/items/crear-desde-cero/",
    "/analisis-precio-unitario/items/importar-desde-esfera/",
    "/analisis-precio-unitario/items/importar-desde-excel/",
    "/compras/",
    "/compras/pedidos/",
    "/compras/cotizaciones/",
    "/compras/autorizaciones/",
    "/compras/ordenes-de-compra/",
    "/obra/",
    "/obra/avances/",
    "/obra/planillas/",
    "/obra/retenciones/",
    "/almacen/",
    "/almacen/entradas/",
    "/almacen/salidas/",
    "/almacen/stock/",
    "/cartera/",
    "/cartera/clientes/",
    "/cartera/inmuebles/",
    "/cartera/ventas/",
    "/cartera/galeria/",
    "/prefactibilidad/",
  ];

  return routes.map((route) => ({
    url: `${BASE_URL}${route}`,
    lastModified: new Date(),
    changeFrequency: "monthly" as const,
    priority: route.split("/").filter(Boolean).length === 1 ? 0.8 : 0.7,
  }));
}
